image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

job1:
    stage: build
    script:
        - 'mvn test'
        - 'mvn compile'
        - 'mvn package'
    only:
        - master
    tags:
        - docker
