cache:
  paths:
    - .m2/repository

image: maven:3.3.9-jdk-8

job:bluild:
stage: build
  script:
    - 'mvn test'
    - 'mvn compile'
  only:
    - master
  tags:
    - docker

job:package:
stage: build
  script:
    - 'mvn package'
  only:
    - master
  tags:
    - docker




