image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository


job1:
    stage: build
    script:
        - 'mvn test'
        - 'mvn compile'
    only:
        - master
    tags:
        - docker

job2:
    stage: build
    script:
        - 'mvn package'
    only:
        - master
    tags:
        - docker




