image: maven:3.3.9-jdk-8

cache:
  paths:
    - /builds/XsrTeam/BattleCardRM

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/builds/XsrTeam/BattleCardRM"

job1:
    stage: build
    script:
        - 'mvn test'
        - 'mvn compile'
        - 'mvn package'
    only:
        - master
    tags:
        - docker
